# Generated by Django 3.1.5 on 2021-01-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_death',
        ),
    ]
