# Generated by Django 3.1.5 on 2021-01-19 19:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210118_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotations',
            name='content',
        ),
        migrations.AlterField(
            model_name='quotations',
            name='conten_quotations',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Alıntılar'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Alıntı')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
